/**
 * GitHub Writeback Service
 *
 * Core service layer for committing documents and prototypes to GitHub repositories.
 * Uses Convex for workspace/project data (replaces Drizzle + githubWriteOps audit table).
 *
 * Note: The githubWriteOps audit log has been removed — operations are logged to console.
 * A Convex audit table can be added in a future phase if needed.
 */

import type {
  WritebackConfig,
  WritebackFile,
  WritebackResult,
  CommitMetadata,
} from "./types";
import { nanoid } from "nanoid";
import { getGitHubClient } from "./auth";
import {
  getConvexWorkspace,
  getConvexProjectWithDocuments,
  listConvexWorkspaceMembers,
} from "@/lib/convex/server";

/**
 * Slugifies a project name for use in commit messages.
 */
function slugifyForCommit(projectName: string): string {
  return projectName
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "");
}

/**
 * Generates an atomic commit message with project context.
 *
 * Pattern: docs({project-slug}): {action} {document-type}
 * Example: "docs(feature-alpha): add prd"
 */
export function generateCommitMessage(
  metadata: CommitMetadata,
  action: "add" | "update" = "add"
): string {
  const slug = slugifyForCommit(metadata.projectName);
  const docType = metadata.documentType?.replace(/_/g, "-") || "document";

  const lines = [
    `docs(${slug}): ${action} ${docType}`,
    "",
    `Project: ${metadata.projectName}`,
    `Generated by: Elmer${metadata.triggeredBy ? ` (${metadata.triggeredBy})` : ""}`,
  ];

  if (metadata.stageRunId) {
    lines.push(`Stage run: ${metadata.stageRunId}`);
  }

  return lines.join("\n").trim();
}

/**
 * Commits files to GitHub using authenticated Octokit client.
 *
 * @param config - Writeback configuration (workspace, project, repo details)
 * @param files - Array of files to commit
 * @param metadata - Commit metadata for message generation
 * @param userId - User ID for GitHub authentication
 * @param action - Whether adding or updating files
 * @returns WritebackResult with success status and commit details
 */
export async function commitToGitHub(
  config: WritebackConfig,
  files: WritebackFile[],
  metadata: CommitMetadata,
  userId: string,
  action: "add" | "update" = "add"
): Promise<WritebackResult> {
  const message = generateCommitMessage(metadata, action);
  const opId = `ghop_${nanoid()}`;

  try {
    const octokit = await getGitHubClient(userId);
    if (!octokit) {
      return {
        success: false,
        error: "GitHub not connected. Please reconnect your GitHub account.",
      };
    }

    console.log(`[writeback-service] Starting commit op=${opId} repo=${config.owner}/${config.repo} files=${files.length}`);

    // Get current branch ref
    const { data: refData } = await octokit.git.getRef({
      owner: config.owner,
      repo: config.repo,
      ref: `heads/${config.branch}`,
    });

    const parentSha = refData.object.sha;
    const { data: commitData } = await octokit.git.getCommit({
      owner: config.owner,
      repo: config.repo,
      commit_sha: parentSha,
    });

    // Create tree entries for files
    const tree = files.map((file) => ({
      path: file.path,
      mode: "100644" as const,
      type: "blob" as const,
      content: file.content,
    }));

    // Create new tree
    const { data: newTree } = await octokit.git.createTree({
      owner: config.owner,
      repo: config.repo,
      base_tree: commitData.tree.sha,
      tree,
    });

    // Create commit
    const { data: newCommit } = await octokit.git.createCommit({
      owner: config.owner,
      repo: config.repo,
      message,
      tree: newTree.sha,
      parents: [parentSha],
    });

    // Update branch ref
    await octokit.git.updateRef({
      owner: config.owner,
      repo: config.repo,
      ref: `heads/${config.branch}`,
      sha: newCommit.sha,
    });

    console.log(`[writeback-service] Committed op=${opId} sha=${newCommit.sha}`);

    return {
      success: true,
      commitSha: newCommit.sha,
      commitUrl: `https://github.com/${config.owner}/${config.repo}/commit/${newCommit.sha}`,
      filesWritten: files.map((f) => f.path),
    };
  } catch (error) {
    console.error("[writeback-service] Commit failed:", error);

    return {
      success: false,
      error: error instanceof Error ? error.message : "Failed to commit to GitHub",
    };
  }
}

/**
 * Gets the writeback configuration for a project from workspace settings.
 * Uses Convex for workspace and project data.
 */
export async function getWritebackConfig(
  workspaceId: string,
  projectId: string
): Promise<WritebackConfig | null> {
  const [project, workspace] = await Promise.all([
    getConvexProjectWithDocuments(projectId),
    getConvexWorkspace(workspaceId),
  ]);

  if (!project || !workspace) {
    return null;
  }

  if (!workspace.githubRepo) {
    return null;
  }

  const [owner, repo] = (workspace.githubRepo as string).split("/");
  if (!owner || !repo) {
    return null;
  }

  const settings = (workspace.settings as Record<string, unknown>) ?? {};

  return {
    workspaceId,
    projectId,
    projectName: project.name as string,
    owner,
    repo,
    branch: (settings.baseBranch as string) || "main",
    basePath: "initiatives",
  };
}

/**
 * Checks if a workspace has writeback enabled (GitHub connected with valid repo).
 * Uses Convex for workspace data.
 */
export async function isWritebackEnabled(workspaceId: string): Promise<boolean> {
  const workspace = await getConvexWorkspace(workspaceId);
  if (!workspace?.githubRepo) {
    return false;
  }
  const [owner, repo] = (workspace.githubRepo as string).split("/");
  return Boolean(owner && repo);
}

/**
 * Gets the first admin user ID for a workspace (for automated operations).
 * Uses Convex for workspace member data.
 */
export async function getWorkspaceUserId(workspaceId: string): Promise<string | null> {
  const members = await listConvexWorkspaceMembers(workspaceId);
  if (!members || members.length === 0) return null;
  // Return first member (sorted by joinedAt on server)
  return (members[0]?.userId as string) ?? null;
}
