import { defineConfig, devices } from "@playwright/test";

const baseURL = process.env.PLAYWRIGHT_BASE_URL ?? "http://localhost:3000";
const isRemoteBaseURL = /^https?:\/\/(?!localhost(?::|\/|$)|127\.0\.0\.1(?::|\/|$))/.test(
  baseURL,
);

/**
 * Playwright config for Elmer E2E tests.
 *
 * - Local: runs against localhost:3000
 * - CI: reads PLAYWRIGHT_BASE_URL to hit Vercel Preview URLs
 * - Auth: storageState from e2e/.auth/user.json (generated by auth.setup.ts)
 */

export default defineConfig({
  testDir: "./e2e",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI || isRemoteBaseURL ? 1 : undefined,
  reporter: process.env.CI ? [["github"], ["html", { open: "never" }]] : "html",

  use: {
    baseURL,
    trace: "on-first-retry",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
  },

  projects: [
    // Auth setup runs once before all tests
    {
      name: "setup",
      testMatch: /auth\.setup\.ts/,
      use: { storageState: undefined },
    },

    // Primary browser — used in CI
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
        storageState: "e2e/.auth/user.json",
      },
      dependencies: ["setup"],
    },

    // Additional browsers — local only
    ...(process.env.CI
      ? []
      : [
          {
            name: "firefox",
            use: {
              ...devices["Desktop Firefox"],
              storageState: "e2e/.auth/user.json",
            },
            dependencies: ["setup"],
          },
          {
            name: "Mobile Chrome",
            use: {
              ...devices["Pixel 5"],
              storageState: "e2e/.auth/user.json",
            },
            dependencies: ["setup"],
          },
        ]),
  ],

  // Start local dev server automatically when running locally
  webServer: process.env.CI || isRemoteBaseURL
    ? undefined
    : {
        command: "npm run dev",
        url: "http://localhost:3000",
        reuseExistingServer: true,
        timeout: 120_000,
      },
});
