-- Migration: 0014_project_commits.sql
-- Purpose: Track GitHub commits generated by Elmer for each project (WRITE-06, WRITE-07)

CREATE TABLE IF NOT EXISTS "project_commits" (
  "id" text PRIMARY KEY NOT NULL,
  "project_id" text NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
  "workspace_id" text NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE,
  "commit_sha" text NOT NULL,
  "commit_url" text NOT NULL,
  "message" text NOT NULL,
  "document_type" text,
  "files_changed" jsonb DEFAULT '[]',
  "triggered_by" text,
  "stage_run_id" text REFERENCES "stage_runs"("id") ON DELETE SET NULL,
  "github_write_op_id" text REFERENCES "github_write_ops"("id") ON DELETE SET NULL,
  "created_at" timestamp NOT NULL DEFAULT now()
);

-- Index for efficient project history queries
CREATE INDEX IF NOT EXISTS "project_commits_project_id_idx" ON "project_commits"("project_id");

-- Index for workspace-level queries
CREATE INDEX IF NOT EXISTS "project_commits_workspace_id_idx" ON "project_commits"("workspace_id");

-- Index for chronological ordering
CREATE INDEX IF NOT EXISTS "project_commits_created_at_idx" ON "project_commits"("created_at" DESC);
